"""empty message

Revision ID: 177aa11fdf79
Revises: 2f2046f59e47
Create Date: 2021-12-30 10:12:31.818706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '177aa11fdf79'
down_revision = '2f2046f59e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marker', sa.Column('country', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marker', 'country')
    # ### end Alembic commands ###
