"""empty message

Revision ID: 198812880405
Revises: e9ceae74a908
Create Date: 2021-12-30 09:31:16.764062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198812880405'
down_revision = 'e9ceae74a908'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trek', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trek', 'position')
    # ### end Alembic commands ###
