"""empty message

Revision ID: 22e9906884a4
Revises: 461943d1ed90
Create Date: 2021-12-27 15:01:26.054910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22e9906884a4'
down_revision = '461943d1ed90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marker', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marker', 'user', ['user_id'], ['id'])
    op.add_column('route', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'route', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route', type_='unique')
    op.drop_column('route', 'name')
    op.drop_constraint(None, 'marker', type_='foreignkey')
    op.drop_column('marker', 'user_id')
    # ### end Alembic commands ###
