"""empty message

Revision ID: 2f2046f59e47
Revises: 198812880405
Create Date: 2021-12-30 09:36:57.160460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2046f59e47'
down_revision = '198812880405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_marker', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_marker', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
