"""db upgrade

Revision ID: 461943d1ed90
Revises: d766fe6327d0
Create Date: 2021-12-24 22:26:04.965381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461943d1ed90'
down_revision = 'd766fe6327d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_preference_default'), 'preference', ['default'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_profile_default'), 'profile', ['default'], unique=False)
    op.drop_index('ix_option_default', table_name='option')
    op.drop_table('option')
    op.drop_index('ix_mode_default', table_name='mode')
    op.drop_table('mode')
    op.add_column('marker', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('marker', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('marker', sa.Column('elevation', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('distance', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('ascent', sa.Float(), nullable=True))
    op.add_column('route', sa.Column('descent', sa.Float(), nullable=True))
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'trek', ['trek_id'], ['id'])
    op.create_foreign_key(None, 'route', 'profile', ['mode_id'], ['id'])
    op.create_foreign_key(None, 'route', 'preference', ['option_id'], ['id'])
    op.drop_column('route', 'start_id')
    op.drop_column('route', 'end_id')
    op.drop_constraint(None, 'trek', type_='foreignkey')
    op.drop_constraint(None, 'trek', type_='foreignkey')
    op.create_foreign_key(None, 'trek', 'profile', ['mode_id'], ['id'])
    op.create_foreign_key(None, 'trek', 'preference', ['option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trek', type_='foreignkey')
    op.drop_constraint(None, 'trek', type_='foreignkey')
    op.create_foreign_key(None, 'trek', 'option', ['option_id'], ['id'])
    op.create_foreign_key(None, 'trek', 'mode', ['mode_id'], ['id'])
    op.add_column('route', sa.Column('end_id', sa.INTEGER(), nullable=True))
    op.add_column('route', sa.Column('start_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'marker', ['start_id'], ['id'])
    op.create_foreign_key(None, 'route', 'mode', ['mode_id'], ['id'])
    op.create_foreign_key(None, 'route', 'option', ['option_id'], ['id'])
    op.create_foreign_key(None, 'route', 'marker', ['end_id'], ['id'])
    op.drop_column('route', 'descent')
    op.drop_column('route', 'ascent')
    op.drop_column('route', 'distance')
    op.drop_column('marker', 'elevation')
    op.drop_column('marker', 'longitude')
    op.drop_column('marker', 'latitude')
    op.create_table('mode',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('default', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_mode_default', 'mode', ['default'], unique=False)
    op.create_table('option',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('default', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_option_default', 'option', ['default'], unique=False)
    op.drop_index(op.f('ix_profile_default'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_preference_default'), table_name='preference')
    op.drop_table('preference')
    # ### end Alembic commands ###
