"""empty message

Revision ID: a7df7bb559f0
Revises: 0673e0c580f2
Create Date: 2021-12-30 15:55:09.350190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7df7bb559f0'
down_revision = '0673e0c580f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('country', sa.Column('default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_country_default'), 'country', ['default'], unique=False)
    op.create_foreign_key(None, 'marker', 'country', ['country_id'], ['id'])
    op.create_foreign_key(None, 'marker', 'folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marker', type_='foreignkey')
    op.drop_constraint(None, 'marker', type_='foreignkey')
    op.drop_index(op.f('ix_country_default'), table_name='country')
    op.drop_column('country', 'default')
    # ### end Alembic commands ###
