"""empty message

Revision ID: b51310cd4bf0
Revises: 177aa11fdf79
Create Date: 2021-12-30 13:28:32.704372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b51310cd4bf0'
down_revision = '177aa11fdf79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('marker', sa.Column('folder_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marker', 'folder', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marker', type_='foreignkey')
    op.drop_column('marker', 'folder_id')
    op.drop_table('folder')
    # ### end Alembic commands ###
