"""empty message

Revision ID: d69312199305
Revises: b51310cd4bf0
Create Date: 2021-12-30 14:55:35.754350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69312199305'
down_revision = 'b51310cd4bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('marker', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marker', 'country', ['country_id'], ['id'])
    op.create_foreign_key(None, 'marker', 'folder', ['folder_id'], ['id'])
    op.drop_column('marker', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marker', sa.Column('country', sa.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'marker', type_='foreignkey')
    op.drop_constraint(None, 'marker', type_='foreignkey')
    op.drop_column('marker', 'country_id')
    op.drop_table('country')
    # ### end Alembic commands ###
