"""db upgrade

Revision ID: d766fe6327d0
Revises: 85c352e01656
Create Date: 2021-12-24 16:31:38.990821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd766fe6327d0'
down_revision = '85c352e01656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_marker',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('marker_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], ),
    sa.PrimaryKeyConstraint('route_id', 'marker_id')
    )
    op.drop_table('trek_marker')
    op.add_column('route', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('route', sa.Column('trek_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'trek', ['trek_id'], ['id'])
    op.drop_column('route', 'end_id')
    op.drop_column('route', 'start_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route', sa.Column('start_id', sa.INTEGER(), nullable=True))
    op.add_column('route', sa.Column('end_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'route', type_='foreignkey')
    op.create_foreign_key(None, 'route', 'marker', ['end_id'], ['id'])
    op.create_foreign_key(None, 'route', 'marker', ['start_id'], ['id'])
    op.drop_column('route', 'trek_id')
    op.drop_column('route', 'position')
    op.create_table('trek_marker',
    sa.Column('trek_id', sa.INTEGER(), nullable=False),
    sa.Column('marker_id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['marker.id'], ),
    sa.ForeignKeyConstraint(['trek_id'], ['trek.id'], ),
    sa.PrimaryKeyConstraint('trek_id', 'marker_id')
    )
    op.drop_table('route_marker')
    # ### end Alembic commands ###
