"""empty message

Revision ID: e9ceae74a908
Revises: 22e9906884a4
Create Date: 2021-12-29 19:55:14.600340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9ceae74a908'
down_revision = '22e9906884a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trek', type_='foreignkey')
    op.drop_constraint(None, 'trek', type_='foreignkey')
    op.drop_column('trek', 'option_id')
    op.drop_column('trek', 'mode_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trek', sa.Column('mode_id', sa.INTEGER(), nullable=True))
    op.add_column('trek', sa.Column('option_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'trek', 'preference', ['option_id'], ['id'])
    op.create_foreign_key(None, 'trek', 'profile', ['mode_id'], ['id'])
    # ### end Alembic commands ###
